export const url = {

    login: 'auth/sign-in',
    create_user: 'authentication/register',
    delete_user: 'user/',
    change_password: 'user/password/update',
    user_update: 'user/update/',
    logout: 'auth/logout',
  list_users: 'user/list',
  me: 'user/me',
  patient : 'patient',
  patientName: 'patient/list',
  rendezvous: 'rendezvous',
  consultation: 'consultation',
  prescription: 'prescription',
  report_prescription_list: 'prescription/report/list',
  report_download: 'prescription/report/',
  report_generated: 'prescription/report',
  report_consultation: 'consultation/report',
  fichier_patient: 'consultation/fichiers/',
  fichier_download: 'consultation/fichier/',
  delete_file: 'consultation/fichier/delete/',
  consul_report: 'consultation/report/',
  prescription_report: 'prescription/report/',
  hopital_lst: 'consultation/hopital/',
  medicament_list: 'consultation/medicament/',
  prescription_md: 'prescription/medicament/',
  habitudes : 'consultation/habitude/',
  addCaisse: 'caisse/add',
  updaeCaisse :'caisse/update/',
  caisseList: 'caisse/list',
  logo : 'logo/name',
  profile: 'user/profile/add',
  antecedent: 'consultation/antecedent',
  file_patient_import: 'consultation/fichier',
  etablissement: 'etablissement',
  agent_setEquipe: 'agent/associer',
  agent_search: 'agent/search',
  agent_list: 'agent/list',
  agent_add: 'agent/add',
  agent_findOne: 'agent/',
  agent_filter: 'agent/filter',
  donne_agent_list: 'donnee/list',
  donnee_agent_add: 'donnee/add',
  donnee_Equipe_list: 'equipe/my-data',
  myprofile: 'user/profile',
  role_update: 'user/update-role',
  equipe_add: 'equipe/add',
  equipe_list: 'equipe/list',
  equipe_update: 'equipe/update',
  dashboardItems: "dashboard/itemsSize",
  excel: "donnee/download"





}
